### ISSUE TITLE
Process: code reviewer per story/PBI

### ISSUE THREAD

**Issue by debugerr** [microsoft/code-with-engineering-playbook#103]
- having a code reviewer assigned per user story / task?
- that would help with discipline and planning the effort
- how do you make the effort predictable with changing PR size?

**Comment by TessFerrandez** [comment]
This issue seems to be at least partially covered already in the PR General Guidance.

- In the daily standup meeting check tasks pending for review and make sure they have reviewers assigned.
- Junior teams and teams new to the process can consider creating separate tasks for reviews together with the tasks themselves.

Regarding having a code reviewer assigned per user story / task, I don't agree with this. Assigning a task or a PR to someone before it can actually be worked on can create problems as that person may or may not be available to work on it when it needs to be done.  I am also unsure how that would help with discipline and planning effort.  

We already have guidance around adding relevant reviewers, and making sure that PRs get owners.

I also don't understand the 3rd point here, "how do you make the effort predictable with changing PR size" can we elaborate on this?

**Comment by TessFerrandez** [comment]
Closing per discussion on teams
