### ISSUE TITLE
Add recipe on how to create a static website for your documentation based on mkdocs and mkdocs-material

### ISSUE THREAD

**Issue by magencio** [microsoft/code-with-engineering-playbook#689]
Add recipe to [Documentation section](https://github.com/microsoft/code-with-engineering-playbook/tree/main/docs/documentation) on how to create a static website for your documentation based on mkdocs and mkdocs-material, which could be based on the work done with the Playbook itself:

#607 MKDocs integration
#608 Mkdocs Github Action
#618 Feature/clean up doc structure after mkdocs

It would be great if @omri374 could take this, as he did the work on the Playbook.

**Comment by omri374** [comment]
Hey @magencio I don't think I'll have capacity for this but if be happy to provide details to whoever takes this.

**Comment by magencio** [comment]
Hi @omri374 , I will take this then. So please, provide those details to me. Thank you very much.

**Comment by omri374** [comment]
Hi @magencio,
MKDocs is a tool built to create static websites from raw markdown files. Other alternatives include [Sphinx](https://www.sphinx-doc.org/en/master/) and [Jekyll](https://jekyllrb.com/). We found MKDocs to be a good choice since:
1. It's easy to set up and looks great even with the vanilla version.
2. It works well with markdown, which is what we already have in the playbook.
3. It uses a Python stack which is friendly to many contributors of this playbook. 

For comparison, Sphynx mainly generates docs from restructured-text (rst) format, and Jekyll is written in Ruby.

To setup an mkdocs website, the main assets needed are:
1. an `mkdocs.yaml` file, similar to the one we have [in our repo](https://github.com/microsoft/code-with-engineering-playbook/blob/main/mkdocs.yml). This is the configuration file that defines the appearance of the website, the navigation, the plugins used and more.
2. A Github action for automatically generating the website (e.g. on every commit to main), similar to [this one from our repo](https://github.com/microsoft/code-with-engineering-playbook/blob/main/.github/workflows/mkdocs.yml).
3. A list of plugins used during the build phase of the website. We specified ours [here](https://github.com/microsoft/code-with-engineering-playbook/blob/main/requirements-docs.txt).

Setting up locally is also very easy (see some documentation [here](https://www.mkdocs.org/getting-started/)). For publishing the website, there's a [good integration with Github for storing the website as a Github Page](https://www.mkdocs.org/user-guide/deploying-your-docs/).

The plugins we've used:
1. [Material for MKDocs](https://squidfunk.github.io/mkdocs-material/): Material design appearance and user experience.
2. [pymdown-extensions](https://facelessuser.github.io/pymdown-extensions/): Improves the appearance of markdown based content.
3. [mdx_truly_sane_lists](https://github.com/radude/mdx_truly_sane_lists): For defining the indent level for lists without having to refactor the entire documentation we already had in the playbook.

Hope this helps to get started! feel free to reach out if you have any questions.
