### ISSUE TITLE
Investigate and make recommendations on Open Hack content

### ISSUE THREAD

**Issue by NarmathaBala** [microsoft/code-with-engineering-playbook#737]
.https://dev.azure.com/cseeest/OpenHack/_git/Managing_Prod_Env	
The sample application that was being used is @ https://github.com/Azure-Samples/openhack-production
Individual challenge content is @ https://dev.azure.com/cseeest/OpenHack/_git/Managing_Prod_Env?path=%2Fportal%2Fen

Understand the existing open hack content and make recommendations if the content should be expanded. If so, what ares?

**Comment by MagdaPaj** [comment]
Ideas:
- expand alerts: not only metric alerts, but add log based alerts (stateless, stateful), activity log based alerts (if makes sense)
- expand logging: helping users to learn/practice Kusto queries and create a dashboard with them. It could be useful as part of the Postmortem & Root Cause Analysis
- add infrastructure monitoring, maybe it could be as part of the scaling challenge and help with identifying performance bottlenecks
- add dashboards/workbooks, it could be part as part of the global launch or maintenance challenge
- automate creation of alerts/dashboards (potential tools: ARM templates, terraform, PowerShell, Bicep)

**Comment by TessFerrandez** [comment]
@narmathabala @MagdaPaj and @ams0 - this issue seems to be related to open hack and not the playbook itself, or would the content in the playbook be updated as well? Either way, is this issue still relevant and active or ok to close?
